### ISSUE TITLE
Notified by User: 2 INCC are generated for same sector || Kodakara Town_10.189.128.2 

### ISSUE THREAD

**Issue by sohailshaikh-tm** [puneet-tm/wirelessone-support#70]
2 INCC are generated for same sector after manual fired from down tab.

**Comment by rupalivaidya-tm** [comment]
Issue Resolved.

**RCA:** Issue occurred due to new changes done in W1 where new configuration for auto ticketing configured as sector having customers less than 4 then auto ticket will generate after 30 min else more than 4 customers ticket will generate within 15min. 
Issue occurred due to manual ticket was fired in that sector as well as auto ticket also generated after 15/30 min. 

Now necessary changes have been done so that this kind of cases will not occur in future.

**Comment by rupalivaidya-tm** [comment]
@rohitgupta-tm : Please check the RCA and resolve this Issue.

**Comment by rohitgupta-tm** [comment]
@rupalivaidya-tm : correct RCA
