### ISSUE TITLE
User Notified: BH polling fail report issue

### ISSUE THREAD

**Issue by rupalivaidya-tm** [puneet-tm/wirelessone-support#94]
Observing issue in BH polling failure report.
For devices BH utilization is not available in w1 but in polling failure report, status is showing blank.

**Comment by santoshkhairnar-tm** [comment]
For below three IPs snmp response is too slow  that's way snmpwalk is not completed 
10.175.91.102,
10.226.69.66,
10.189.251.6
And For remaining IPs snmp not running showing Timeout Error so that way utilization graph not showing.
Utilisation graph already shown for 10.160.199.26
RCA: SNMP Walk issue
